
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_SUCCEED = 'GET_QUESTIONS_SUCCEED';
export const GET_QUESTIONS_FAILED = 'GET_QUESTIONS_FAILED';

export const GET_ROLES ='GET_ROLES';
export const GET_ROLES_SUCCEED = 'GET_ROLES_SUCCEED';
export const GET_ROLES_FAILED = 'GET_ROLES_FAILED';

export const GET_MAPPINGS ='GET_MAPPINGS';
export const GET_MAPPINGS_SUCCEED = 'GET_MAPPINGS_SUCCEED';
export const GET_MAPPINGS_FAILED = 'GET_MAPPINGS_FAILED';

export const POST_QUESTIONS = 'POST_QUESTIONS';
export const POST_QUESTIONS_SUCCEED = 'POST_QUESTIONS_SUCCEED';
export const POST_QUESTIONS_FAILED = 'POST_QUESTIONS_FAILED';

export const EDIT_QUESTIONS = 'EDIT_QUESTIONS';
export const EDIT_QUESTIONS_SUCCEED = 'EDIT_QUESTIONS_SUCCEED';
export const EDIT_QUESTIONS_FAILED = 'EDIT_QUESTIONS_FAILED';

export const DELETE_QUESTIONS = 'DELETE_QUESTIONS';
export const DELETE_QUESTIONS_SUCCEED = 'DELETE_QUESTIONS_SUCCEED';
export const DELETE_QUESTIONS_FAILED = 'DELETE_QUESTIONS_FAILED';